name: test

on:
  push:

env:
  VERSION: TEST_$(date + '%Y%m%d%H%M')

jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        envs: [dev-eu, dev-us, dev-cn, stg-eu, stg-us, prd, prd-cn]
    steps:
      - name: artifact version
        run: |
          echo "${{ env.VERSION }} + ${{ matrix.envs }}" > version.txt
          cat version.txt
      - name: Upload artifact version
        uses: actions/upload-artifact@v4
        with:
          name: version-${{ matrix.envs }}
          path: |
            version.txt

  download:
    needs: [ upload ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        envs: [dev-eu, dev-us, dev-cn, stg-eu, stg-us, prd, prd-cn]
    steps:
      - name: test
        run: |
          pwd
          ls -al
      - name: Download artifact version
        uses: actions/download-artifact@v4
        with:
          name: version-${{ matrix.envs }}
          path: |
            ./artifacts
      - name: check
        run: |
          cd artifacts
          pwd
          ls -al
          cat version.txt
