name: test

on:
  push:

env:
  ARTIFACT_NAME: html.tar.gz

jobs:
  artifacts-version:
    runs-on: ubuntu-latest
    steps:
      # version
      - name: Set VERSION env
        run: echo "VERSION=TEST_$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - name: artifact version
        run: |
          echo "${{ env.VERSION }}" > versions.txt
          cat versions.txt
      - name: Upload artifact version
        uses: actions/upload-artifact@v4
        with:
          name: versions
          path: versions.txt

  source-build:
    needs: [ artifacts-version ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        envs: [dev-eu, dev-us, dev-cn, stg-eu, stg-us] #, prd, prd-cn]
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: Set and verify ENV_VAR_LIST
        run: |
          case "${{ matrix.envs }}" in
            dev-eu|dev-us)
              printf 'NEXT_PUBLIC_ENVIRONMENT=%s\n' "$DEV_ENV" >> "$GITHUB_ENV"
              ;;
            dev-cn)
              printf 'NEXT_PUBLIC_ENVIRONMENT=%s\n' "$DEV_ENV" >> "$GITHUB_ENV"
              printf 'NEXT_PUBLIC_SA_URL=%s\n' "$CN_SA_URL" >> "$GITHUB_ENV"
              ;;
            *)
              echo "No env vars needed for ${{ matrix.envs }}"
              ;;
          esac

          # if [ "${{ matrix.envs }}" = "dev-eu" ] || [ "${{ matrix.envs }}" = "dev-us" ]; then
          #   echo 'NEXT_PUBLIC_ENVIRONMENT=${{ secrets.DEV_NEXT_PUBLIC_ENVIRONMENT }}' >> $GITHUB_ENV
          # elif [ "${{ matrix.envs }}" = "dev-cn" ]; then
          #   echo "NEXT_PUBLIC_ENVIRONMENT=${{ secrets.DEV_NEXT_PUBLIC_ENVIRONMENT }}" >> $GITHUB_ENV
          #   echo "NEXT_PUBLIC_SA_URL=${{ secrets.NEXT_PUBLIC_SA_URL_CN }}" >> $GITHUB_ENV
          # elif [ "${{ matrix.envs }}" = "stg-eu" ] || [ "${{ matrix.envs }}" = "stg-us" ]; then
          #   echo "NEXT_PUBLIC_ENVIRONMENT=${{ secrets.STG_NEXT_PUBLIC_ENVIRONMENT }}" >> $GITHUB_ENV
          # elif [ "${{ matrix.envs }}" = "prd" ]; then
          #   echo "NEXT_PUBLIC_ENVIRONMENT=${{ secrets.PRD_NEXT_PUBLIC_ENVIRONMENT }}" >> $GITHUB_ENV
          # elif [ "${{ matrix.envs }}" = "prd-cn" ]; then
          #   echo "NEXT_PUBLIC_ENVIRONMENT=${{ secrets.PRD_NEXT_PUBLIC_ENVIRONMENT }}" >> $GITHUB_ENV
          #   echo "NEXT_PUBLIC_SA_URL=${{ secrets.NEXT_PUBLIC_SA_URL_CN }}" >> $GITHUB_ENV
          # fi

          ENV_VAR_LIST=(NEXT_PUBLIC_ENVIRONMENT NEXT_PUBLIC_SA_URL)
          for ENV_VAR in "${ENV_VAR_LIST}"
          do
            echo '::'_${ENV_VAR}
            if [ -z "${!ENV_VAR}" ]; then
              echo "${ENV_VAR}" is empty"
            else
              echo "read ${ENV_VAR}"
            fi
          done

      - name: Replace 'self_url' on testfile.html
        run: |
          sed -i "s|{{self_url}}|${{ matrix.url }}|g" testfile.html
          cat testfile.html          
      - name: compression to artifacts
        run: tar -czf html.tar.gz testfile.html
      - name: Upload artifact version
        uses: actions/upload-artifact@v4
        with:
          name: html-${{ matrix.envs }}
          path: |
            ./${{ env.ARTIFACT_NAME }}
          overwrite: true

  image-build:
    needs: [ source-build ]
    runs-on: ubuntu-latest
    env:
      ECR_STG_REGISTRY: 1234
      ECR_STG_REPOSITORY: test
    strategy:
      matrix:
        envs: [dev-eu, dev-us, dev-cn, stg-eu, stg-us] #, prd, prd-cn]
    steps:
      - name: Download artifact version
        uses: actions/download-artifact@v4
        with:
          name: versions
          path: |
            ./artifacts
      - name: check
        run: |
          cd artifacts
          pwd
          ls -al
          cat versions.txt

      - name: Build docker image
        run: |
          echo "Build docker image"
          IMAGE_TAG=$(cat ./artifacts/versions.txt)
          echo "Using version: $IMAGE_TAG"

          # docker build -t ${{ env.ECR_STG_REGISTRY }}/${{ env.ECR_STG_REPOSITORY }}:$IMAGE_TAG .
          # docker push ${{ env.ECR_STG_REGISTRY }}/${{ env.ECR_STG_REPOSITORY }}:$IMAGE_TAG
          # echo "Image pushed: ${{ env.ECR_STG_REGISTRY }}/${{ env.ECR_STG_REPOSITORY }}:$IMAGE_TAG"